### ISSUE TITLE
after modal closed, the modal mask still exist. 

### ISSUE THREAD

**Issue by pokemonfan7** [NG-ZORRO/ng-zorro-antd-mobile#335] opened 2019-03-12 03:21 UTC
## Version
0.11.6
## Environment
angular6.1.1
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-mobile-start-ukedw4](https://stackblitz.com/edit/ng-zorro-antd-mobile-start-ukedw4)
## Steps to reproduce
your doc also has the bug.  click alert promise and then you cannot click another btn because of the alert mask exisits
http://ng.mobile.ant.design/#/components/modal/en
## What is expected?
close the modal , the modal mask disappear.
## What is actually happening?
close the modal , the modal mask still exist. 
## Other?
中文文档：http://ng.mobile.ant.design/#/components/modal/zh  ，右侧示例的警告弹窗中的promise，点击之后，然后关闭，遮罩层依旧存在，classname是am-modal-mask，因为这个遮罩层的存在，使得页面其他操作例如按钮点击不能完成，造成页面假死的效果

**Comment by pokemonfan7** [comment] 2019-03-12 03:43
in my localhost it's no problem, but in production website, it exisits.

**Comment by Guoyuanqiang** [comment] 2019-03-12 05:59
Duplicate of #332

**Closed** 2019-03-12 07:17 UTC
